skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
open_bounty = "DNLHZMdnmgxpWWYbqdNcp5xLqvyJ6zxonn27qUAveGch"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
